### ISSUE TITLE
Missing libpyqt5.so

### ISSUE THREAD

**Issue by hhslepicka** [conda-forge/pyqt-feedstock#44]
Issue:
On previous releases of the PyQt package for this channel the PyQt plugin was available but at the latest it is gone.

- `pyqt-5.6.0-py36h8210e8a_8.tar.bz2` includes the plugin under <>/plugins/designer/libpyqt5.so
- `pyqt-5.6.0-py36h13b7fb3_1008.tar.bz2` is missing it.

What changed?
Can we have a release with the plugin back?
If not, what is the recommended approach?

Thank you

**Comment by CJ-Wright** [comment]
The reason is that the newer version has been built with gcc7.
Relevent PRs: 
https://github.com/conda-forge/pyqt-feedstock/pull/41
https://github.com/conda-forge/pyqt-feedstock/pull/42

**Comment by CJ-Wright** [comment]
Also:
attn: @conda-forge/pyqt

**Comment by hhslepicka** [comment]
@CJ-Wright exactly.
I'm wondering if a patch to `configure.py` would be a good way out of this situation.

**Comment by CJ-Wright** [comment]
I have no idea. At this point I'd put up a PR and see if it works. People may be able to comment better on a PR than an issue.

**Comment by ocefpaf** [comment]
@hhslepicka please test this against the new packages and, if the problem persists, re-open the issue.

**Comment by hhslepicka** [comment]
@ocefpaf the library is there now but with linking issues. The new issue is open.

**Comment by ludmilaklenova** [comment]
Update for PyQt6 users — June 2026

Good news: the libpyqt6.so Designer plugin is now included directly in the official conda-forge pyqt6 package (PR #184 — merged). 
It is installed automatically at:
$CONDA_PREFIX/lib/qt6/plugins/designer/libpyqt6.so
Available platforms and Python ≥ 3.10 (build _1):

- linux-64
- linux-aarch64
- osx-64
- osx-arm64 (Apple Silicon)
- win-64

To get the plugin, simply install the latest build:
mamba install -c conda-forge "pyqt6=*=*_1"

or wait for it to become the default (build _0 is still default in some repodata caches)

Note: osx-64 Python 3.10 and win-64 Python 3.12 are missing from build _1 due to transient CI failures (DNS / rate limiting). A rebuild has been requested.
